module.exports = {
  apps: [
    {
      name: 'trading-engine',
      script: 'dist/src/index.js',
      interpreter: 'node',
      cwd: 'C:\\trading-engine',
      env: {
        NODE_ENV: 'production',
      },
      min_uptime: '30s',
      restart_delay: 5000,
      max_restarts: 20,
      autorestart: true,
      watch: false,
      exp_backoff_restart_delay: 1000,
      max_memory_restart: '1G',
      kill_timeout: 10000,
      listen_timeout: 10000,
      error_file: 'logs/pm2-error.log',
      out_file: 'logs/pm2-out.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'dashboard',
      script: 'npm',
      args: 'run start:dashboard:prod',
      cwd: 'C:\\trading-engine',
      env: {
        NODE_ENV: 'production',
      },
      min_uptime: '30s',
      restart_delay: 3000,
      autorestart: true,
      watch: false,
      exp_backoff_restart_delay: 1000,
      kill_timeout: 10000,
      error_file: 'logs/pm2-dashboard-error.log',
      out_file: 'logs/pm2-dashboard-out.log',
      merge_logs: true,
      time: true,
    },
  ],
};
